import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { detectModeCollections, type TokenTree } from '../sd.preprocessors.ts';
import { buildModeTokens, type FlatToken } from './mode-build.ts';
import {
  flattenForMode,
  toCamelCase,
  classifyResolvedNumeric,
} from './flatten-tokens.ts';

/**
 * Emits a Kotlin source file for native Android consumption -- one
 * `object` singleton (Kotlin's pure constant-namespace pattern) per
 * color x density mode combo, mirroring build-swift.ts's shape.
 *
 * Kotlin objects, not XML resources: Android's own resource-qualifier
 * system (`values-night/`, `values-sw600dp/`, ...) already models
 * dark-mode and *screen*-density variance, but "roomy"/"condensed" here
 * is a UI-density concept unrelated to screen density (mdpi/hdpi/...) --
 * reusing that qualifier folder convention for it would collide in name
 * only, not meaning. Plain Kotlin objects sidestep that name clash and
 * keep the same "4 resolved sets + host app picks one" shape as
 * build-js.ts/build-swift.ts, rather than inventing a second, XML-based
 * mode-selection mechanism for one platform alone.
 *
 * No concrete consumer exists in this repo (no Android app); this exists
 * to demonstrate the full cross-platform token pipeline for the
 * portfolio. Kept deliberately data-only, same reasoning as
 * build-swift.ts.
 *
 * Value typing: color / fontFamily as `String` (hex / family name, as
 * resolved) -- a real app converts to `androidx.compose.ui.graphics.Color`
 * / `FontFamily` itself. dimension / fontWeight / other numbers as
 * `Double` (unitless -- Android dp, not CSS "px"; 1 px == 1 dp, the same
 * simplification build-swift.ts makes for pt).
 */

const MODE_COMBOS = [
  { scheme: 'light', density: 'roomy' },
  { scheme: 'dark', density: 'roomy' },
  { scheme: 'light', density: 'condensed' },
  { scheme: 'dark', density: 'condensed' },
] as const;

function kotlinLiteral(token: FlatToken): string {
  if (token.declaredType === 'color' || token.declaredType === 'fontFamily') {
    return `"${token.value}"`;
  }
  const kind = classifyResolvedNumeric(token);
  const n =
    kind === 'dimension'
      ? Number(token.value.replace(/px$/, ''))
      : Number(token.value);
  return String(n);
}

function kotlinType(token: FlatToken): 'String' | 'Double' {
  return token.declaredType === 'color' || token.declaredType === 'fontFamily'
    ? 'String'
    : 'Double';
}

function objectName(scheme: string, density: string): string {
  return `${scheme[0].toUpperCase()}${scheme.slice(1)}${density[0].toUpperCase()}${density.slice(1)}Tokens`;
}

async function main() {
  const sourceTree = JSON.parse(
    readFileSync(resolve('source/tokens.json'), 'utf8'),
  ) as TokenTree;
  const modeCollections = detectModeCollections(sourceTree);

  const lines: string[] = [
    '// Generated by scripts/build-kotlin.ts -- do not hand-edit. Run `pnpm --filter tokens build:kotlin`.',
    '',
    'package tokens',
    '',
  ];

  let total = 0;
  for (const { scheme, density } of MODE_COMBOS) {
    const tokens = await buildModeTokens({ color: scheme, density });
    const flat = flattenForMode(tokens, modeCollections, {
      color: scheme,
      density,
    });
    const entries = flat
      .map(
        (t) =>
          [toCamelCase(t.name), kotlinType(t), kotlinLiteral(t)] as [
            string,
            string,
            string,
          ],
      )
      .sort(([a], [b]) => a.localeCompare(b));
    total += entries.length;

    lines.push(`object ${objectName(scheme, density)} {`);
    for (const [name, type, literal] of entries) {
      lines.push(`    const val ${name}: ${type} = ${literal}`);
    }
    lines.push('}', '');
  }

  const buildDir = resolve(
    dirname(fileURLToPath(import.meta.url)),
    '../build/kotlin',
  );
  mkdirSync(buildDir, { recursive: true });
  writeFileSync(resolve(buildDir, 'Tokens.kt'), lines.join('\n'));

  console.log(
    `Wrote build/kotlin/Tokens.kt (${total} entries across 4 mode combos)`,
  );
}

main();
