import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { detectModeCollections, type TokenTree } from '../sd.preprocessors.ts';
import { buildModeTokens, type FlatToken } from './mode-build.ts';
import {
  flattenForMode,
  toCamelCase,
  classifyResolvedNumeric,
} from './flatten-tokens.ts';

/**
 * Emits a plain TS module of fully-resolved token values -- one flat
 * object per color x density mode combination, mirroring build-dtcg.ts's
 * per-combo file split (see flatten-tokens.ts for the shared filtering).
 * For consumers that can't read CSS custom properties at all (React
 * Native, non-DOM JS logic) or that need a token as an actual JS value
 * rather than a string to interpolate into a stylesheet -- e.g. a Radix
 * primitive's numeric `sideOffset` prop, the concrete motivating case for
 * this format.
 *
 * Value typing deliberately differs from build-dtcg.ts's DTCG output:
 * - color / fontFamily: string, as resolved (e.g. "#0B5FFF").
 * - dimension (resolved value ends in "px"): unitless `number`, with the
 *   "px" stripped -- NOT a unit-suffixed string. DTCG requires units on
 *   its "dimension" type, but a JS consumer computing with a token (an
 *   offset passed to a component prop, a value added/multiplied in
 *   layout logic) wants a plain number, not a string it has to parse
 *   first. This is the one deliberate divergence from the DTCG format.
 * - fontWeight / other unitless numbers: plain `number`.
 *
 * Mode strategy: no CSS cascade exists in plain JS, so all 4 resolved
 * combos ship side by side and the host app picks the active one itself
 * (via `getTokens`), the same way a React Native app already tracks its
 * own color scheme / density state. This is a deliberate, discussed
 * choice, not an oversight -- see the "Mode strategy" decision in this
 * package's design conversation.
 */

const MODE_COMBOS = [
  { scheme: 'light', density: 'roomy' },
  { scheme: 'dark', density: 'roomy' },
  { scheme: 'light', density: 'condensed' },
  { scheme: 'dark', density: 'condensed' },
] as const;

function jsValue(token: FlatToken): string | number {
  if (token.declaredType === 'color' || token.declaredType === 'fontFamily') {
    return token.value;
  }
  const kind = classifyResolvedNumeric(token);
  return kind === 'dimension'
    ? Number(token.value.replace(/px$/, ''))
    : Number(token.value);
}

function exportName(scheme: string, density: string): string {
  return `${scheme}${density[0].toUpperCase()}${density.slice(1)}Tokens`;
}

async function main() {
  const sourceTree = JSON.parse(
    readFileSync(resolve('source/tokens.json'), 'utf8'),
  ) as TokenTree;
  const modeCollections = detectModeCollections(sourceTree);

  const combos = [];
  for (const { scheme, density } of MODE_COMBOS) {
    const tokens = await buildModeTokens({ color: scheme, density });
    const flat = flattenForMode(tokens, modeCollections, {
      color: scheme,
      density,
    });
    const entries = flat
      .map(
        (t) => [toCamelCase(t.name), jsValue(t)] as [string, string | number],
      )
      .sort(([a], [b]) => a.localeCompare(b));
    combos.push({
      scheme,
      density,
      varName: exportName(scheme, density),
      entries,
    });
  }

  const lines: string[] = [
    '// Generated by scripts/build-js.ts -- do not hand-edit. Run `pnpm --filter tokens build:js`.',
    '',
  ];
  for (const combo of combos) {
    lines.push(`export const ${combo.varName} = {`);
    for (const [key, value] of combo.entries) {
      lines.push(
        `  ${key}: ${typeof value === 'string' ? JSON.stringify(value) : value},`,
      );
    }
    lines.push('} as const;', '');
  }

  lines.push(
    "export type ColorScheme = 'light' | 'dark';",
    "export type Density = 'roomy' | 'condensed';",
    '',
    'const tokensByMode = {',
    ...combos.map((c) => `  '${c.scheme}-${c.density}': ${c.varName},`),
    '};',
    '',
    '/** Look up the resolved token set for a given scheme + density -- the',
    ' * JS equivalent of what the CSS cascade resolves automatically via',
    ' * `[data-theme]`/`[data-density]`. The host app owns tracking which',
    ' * scheme/density is active; this only does the lookup. */',
    'export function getTokens(scheme: ColorScheme, density: Density) {',
    '  return tokensByMode[`${scheme}-${density}`];',
    '}',
    '',
  );

  const buildDir = resolve(
    dirname(fileURLToPath(import.meta.url)),
    '../build/js',
  );
  mkdirSync(buildDir, { recursive: true });
  writeFileSync(resolve(buildDir, 'tokens.ts'), lines.join('\n'));

  console.log(
    `Wrote build/js/tokens.ts (${combos.reduce((n, c) => n + c.entries.length, 0)} entries across 4 mode combos)`,
  );
}

main();
