import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { detectModeCollections, type TokenTree } from '../sd.preprocessors.ts';
import { buildModeTokens, type FlatToken } from './mode-build.ts';
import {
  flattenForMode,
  toCamelCase,
  classifyResolvedNumeric,
} from './flatten-tokens.ts';

/**
 * Emits a Swift source file for native iOS consumption -- one `enum`
 * namespace (no cases, so it can't be instantiated -- the standard Swift
 * pattern for a pure constant namespace) per color x density mode combo,
 * mirroring build-js.ts's shape.
 *
 * No concrete consumer exists in this repo (no iOS app); this exists to
 * demonstrate the full cross-platform token pipeline for the portfolio.
 * Kept deliberately data-only: no protocol/lookup-table machinery like
 * build-js.ts's `getTokens` helper, since there's no real call site here
 * to prove that abstraction out. A host app would pick the active enum
 * itself based on its own `ColorScheme`/density state, the same pattern
 * documented in build-js.ts.
 *
 * Value typing: color / fontFamily as `String` (hex / family name, as
 * resolved) -- a real app converts to `UIColor`/`Font` itself, since that
 * conversion is app-specific (asset catalogs, dynamic color, etc.).
 * dimension / fontWeight / other numbers as `Double` (unitless -- iOS
 * points, not CSS "px"; the numeric value carries over unscaled since
 * this pipeline treats 1 px == 1 pt, a simplification with no real device
 * to validate against).
 */

const MODE_COMBOS = [
  { scheme: 'light', density: 'roomy' },
  { scheme: 'dark', density: 'roomy' },
  { scheme: 'light', density: 'condensed' },
  { scheme: 'dark', density: 'condensed' },
] as const;

function swiftLiteral(token: FlatToken): string {
  if (token.declaredType === 'color' || token.declaredType === 'fontFamily') {
    return `"${token.value}"`;
  }
  const kind = classifyResolvedNumeric(token);
  const n =
    kind === 'dimension'
      ? Number(token.value.replace(/px$/, ''))
      : Number(token.value);
  return String(n);
}

function swiftType(token: FlatToken): 'String' | 'Double' {
  return token.declaredType === 'color' || token.declaredType === 'fontFamily'
    ? 'String'
    : 'Double';
}

function enumName(scheme: string, density: string): string {
  return `${scheme[0].toUpperCase()}${scheme.slice(1)}${density[0].toUpperCase()}${density.slice(1)}Tokens`;
}

async function main() {
  const sourceTree = JSON.parse(
    readFileSync(resolve('source/tokens.json'), 'utf8'),
  ) as TokenTree;
  const modeCollections = detectModeCollections(sourceTree);

  const lines: string[] = [
    '// Generated by scripts/build-swift.ts -- do not hand-edit. Run `pnpm --filter tokens build:swift`.',
    '',
    'import Foundation',
    '',
  ];

  let total = 0;
  for (const { scheme, density } of MODE_COMBOS) {
    const tokens = await buildModeTokens({ color: scheme, density });
    const flat = flattenForMode(tokens, modeCollections, {
      color: scheme,
      density,
    });
    const entries = flat
      .map(
        (t) =>
          [toCamelCase(t.name), swiftType(t), swiftLiteral(t)] as [
            string,
            string,
            string,
          ],
      )
      .sort(([a], [b]) => a.localeCompare(b));
    total += entries.length;

    lines.push(`public enum ${enumName(scheme, density)} {`);
    for (const [name, type, literal] of entries) {
      lines.push(`    public static let ${name}: ${type} = ${literal}`);
    }
    lines.push('}', '');
  }

  const buildDir = resolve(
    dirname(fileURLToPath(import.meta.url)),
    '../build/swift',
  );
  mkdirSync(buildDir, { recursive: true });
  writeFileSync(resolve(buildDir, 'Tokens.swift'), lines.join('\n'));

  console.log(
    `Wrote build/swift/Tokens.swift (${total} entries across 4 mode combos)`,
  );
}

main();
