import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const sourceDir = resolve(__dirname, '../source');
const outDir = resolve(__dirname, '../src/generated');
const outFile = resolve(outDir, 'manifest.ts');

const categories: Record<string, string> = JSON.parse(
  readFileSync(resolve(sourceDir, 'categories.json'), 'utf-8'),
);

const iconNames = readdirSync(sourceDir)
  .filter((f) => f.endsWith('.svg'))
  .map((f) => f.replace(/\.svg$/, ''))
  .sort();

const missingCategory = iconNames.filter((name) => !(name in categories));
const orphanedCategory = Object.keys(categories).filter((name) => !iconNames.includes(name));

if (missingCategory.length > 0) {
  throw new Error(
    `source/categories.json is missing entries for: ${missingCategory.join(', ')}`,
  );
}
if (orphanedCategory.length > 0) {
  throw new Error(
    `source/categories.json has entries with no matching SVG: ${orphanedCategory.join(', ')}`,
  );
}

const entries = iconNames
  .map((name) => `  '${name}': { category: '${categories[name]}' },`)
  .join('\n');

const output = `// Generated by scripts/build-manifest.ts from source/categories.json — do not edit by hand.

export interface IconMeta {
  category: string;
}

export const manifest: Record<string, IconMeta> = {
${entries}
};
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, output);
console.log(`Wrote ${iconNames.length} icon entries to ${outFile}`);
